### ISSUE TITLE
How can I format a single java file which I commit but not whole path

### ISSUE THREAD

**Issue by zhujiajun917** [revelc/formatter-maven-plugin#622] opened 2022-05-26 03:21 UTC
**Is your feature request related to a problem? Please describe.**
How can I format a single java file which I commit but not whole path?

**Describe the solution you'd like**
Format a single java file which I commit

**Describe alternatives you've considered**
NA

**Additional context**
As accroding to :
https://github.com/revelc/formatter-maven-plugin/issues/311
I used like this:
in commit-commit git hook I write
```sh
#handle format begin
STAGE_FILES=$(git diff --cached --name-only --diff-filter=ACM -- '*.java')
if test ${#STAGE_FILES} -gt 0
then
    echo 'format java begin...'
    for FILE in $STAGE_FILES
    do
        echo 'formatted file:'$FILE
        mvn -Dformatter.includes=$FILE formatter:format
        #mvn formatter:format
        if [ $? -ne 0 ]; then
            echo 'format:'$FILE 'failed!'
            exit -1
        else
            echo 'format:'$FILE 'ok!'
            git add $FILE
        fi
    done
    echo 'format java end...'
else
    echo 'OK, no java files need to be formatted.'
fi
#handle format end
```
and in pom.xml I write
```xml
            <plugin>
                <groupId>net.revelc.code.formatter</groupId>
                <artifactId>formatter-maven-plugin</artifactId>
                <version>2.18.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>format</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <configFile>${project.basedir}/eclipse-codestyle.xml</configFile>
                    <includes>${formatter.includes}</includes>
                </configuration>
            </plugin>
```

with `mvn -Dformatter.includes=$FILE formatter:format`, It will not format file.
with `mvn formatter:format`, It will not format files more than a single java file which I commit T_T
Thanks again.

**Comment by zhujiajun917** [comment] 2022-05-26 03:25
with mvn -Dformatter.includes=$FILE formatter:format ,It will not format file.
with mvn formatter:format , It will format files more than a single java file which I commit T_T

**Comment by zhujiajun917** [comment] 2022-05-26 03:26
>             <plugin>
                <groupId>net.revelc.code.formatter</groupId>
                <artifactId>formatter-maven-plugin</artifactId>
                <version>2.18.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>format</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <configFile>${project.basedir}/eclipse-codestyle.xml</configFile>
                    <includes>${formatter.includes}</includes>
                </configuration>
            </plugin>

**Comment by zhujiajun917** [comment] 2022-05-26 03:27
> #handle format begin
STAGE_FILES=$(git diff --cached --name-only --diff-filter=ACM -- '*.java')
if test ${#STAGE_FILES} -gt 0
then
    echo 'format java begin...'
	for FILE in $STAGE_FILES
	do
		echo 'formatted file:'$FILE
		echo 'mvn -Dformatter.includes='$FILE 'formatter:format'
		mvn -Dformatter.includes=$FILE formatter:format
		#mvn formatter:format
		if [ $? -ne 0 ]; then
			echo 'format:'$FILE 'failed!'
			exit -1
		else
			echo 'format:'$FILE 'ok!'
			git add $FILE
		fi
	done
	echo 'format java end...'
else
    echo 'OK, no java files need to be formatted.'
fi
#handle format end

**Comment by ctubbsii** [comment] 2022-05-26 13:47
I think you actually need to have your config file look like this to include a single file:

```xml
 <includes>
   <include>${formatter.includes}</include>
 </includes>
```

Also, you don't need to specify the `<executions>` piece to configure it for formatting from the command-line. `<executions>` is for configuring executions of the plugin automatically during a `mvn` build.

**Comment by zhujiajun917** [comment] 2022-05-27 02:50
with   
<includes>
   <include>${formatter.includes}</include>
 </includes>
in pom.xml
And then run mvn formatter:format -Dformatter.includes=src/main/java/com/GitTest.java , it will not format the GitTest.java. @ctubbsii

**Comment by zhujiajun917** [comment] 2022-05-27 02:58
@ctubbsii as your mentioned, I used <include>${formatter.includes}</include> instead of  <includes>${formatter.includes}</includes>,  the result keep the same as before

**Comment by ctubbsii** [comment] 2022-05-27 03:57
I tried this with a wildcard pattern, `mvn formatter:format -Dformatter.includes='**/MyFileName.java'` and that seems to have worked. However, I get the same behavior as you do for specifying the exact path to a file. It's very strange. I'm not sure what the problem is.

**Comment by ctubbsii** [comment] 2022-05-27 04:47
Ah, I figured it out. Apparently, the base directory the formatter is processing files relative to is `src/main/java/` or `src/test/java/` by default.

If you need a different directory, you can set something like:

```xml
            <directories>
              <directory>${project.basedir}</directory>
            </directories>
            <includes>
              <include>${formatter.includes}</include>
            </includes>
```

**Comment by ctubbsii** [comment] 2022-05-27 04:48
Information has been provided. Closing this.

**Closed by ctubbsii** 2022-05-27 04:48 UTC
Labels: question

**Comment by ctubbsii** [comment] 2022-05-28 05:19
@zhujiajun917 No problem. Also, I edited your comment to format the XML correctly. In the future, GitHub users will appreciate you learning to use proper GitHub-flavored Markdown syntax for code blocks: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks
