### ISSUE TITLE
next release

### ISSUE THREAD

**Issue by teleivo** [revelc/formatter-maven-plugin#111] opened 2016-05-27 08:35 UTC
Hi, thanks for the work on this super helpful plugin!

when are you planning to release a new version? somehow I cannot get javascript formatting to work with 0.5.2, but can however with @velo latest 1.6.0 release.

**Comment by ctubbsii** [comment] 2016-05-27 18:21
Right now, I think people's time is limited. We could probably use some additional volunteers/contributor help to create and ship a new release. I also would love a new version to use that does the Mars formatting, myself.

**Comment by hazendaz** [comment] 2016-05-28 21:34
Yes, time is a quite an issue currently.  I know there are some regressions in the current master that need addressed.  For me, getting 0.5.2 through various projects at work and on github was most important.  Now that I'm done with that, I'm looking forward to finding time to work to get the next release out.  As @ctubbsii stated, we need some additional volunteers/contributors to help get the next release going.

**Comment by velo** [comment] 2016-05-28 21:38
Well, I resumed using my own fork, since the bug introduced on git line endings prevent me from using this one.

If you guys wanna see the issue just removed this line
https://github.com/revelc/formatter-maven-plugin/blob/master/appveyor.yml#L16

@teleivo FWIW, 1.6.0 it's a mars release!

**Comment by hazendaz** [comment] 2016-05-28 21:59
@velo can you explain what you mean by bug.  .gitattributes controls line endings.  In windows, it needs to be windows style.  In *nix it needs to be *nix styled.  That is standard usage and even suggested when installing git.  That change specifically was added to fix app voyer at the time as documented that they did not adhere to .gitattributes settings.  The setting in git attributes is exactly that which was set.  Other tools that fail to handle properly is egit.  Recenting appvoyer started failing again, are you saying they did something to change things and that removal will again fix appvoyer?

**Comment by hazendaz** [comment] 2016-05-28 22:02
app voyer still claims that needs to be set [here](http://www.appveyor.com/docs/lang/nodejs-iojs#line-endings}

**Comment by hazendaz** [comment] 2016-05-28 22:43
app voyer was running fine (all green) until pull request 105 / 106.  At that point, the AnyClass.java is getting the 'year' updated to 2016 on appvoyer.  That doesn't happen locally so some git difference possibly.  So I forced the year to 2016 which got the same sha.  This is queued now for build and I will report back shortly...

**Comment by hazendaz** [comment] 2016-05-29 00:09
appvoyer is stable again.

**Comment by velo** [comment] 2016-05-29 00:22
@hazendaz I use windows with default settings, have being doing that since ever....  and for some reason the build no longer works here.  Tests do not pass and I don't wanna change my settings.

**Comment by hazendaz** [comment] 2016-05-29 00:54
@velo If you are willing, try installing GIT again on your machine.  When it is going through installation, make sure you check the correct box to checkout as windows endings in windows, *nix in unix, and check in as *nix.  That is the issue.  It has nothing to do with default settings unless you only use egit (which is crap) to work with git.  For EGIT you have to add that global setting becaues EGIT does not support .gitattributes and has had an outstanding open ticket for at least 5 years to address that.  AppVoyer is not nearly as stable platform as travis ci.  It fails all the time for all kinds of random issues.  But over there the issue is similar to EGIT.  They in fact wrote up documentation stating that fact and how to address it which again is exactly how one would address git in general if using any product that doesn't support gitattributes in combination with proper selection of git checkout style when installing git.

Just let me be clear here.  There is nothing in this configuration that requires anyone to make any special considerations when working with this repo.  When installing 'git for windows' it clearly indicates what is suggested for use and that suggestion for use is exactly what we are enforcing and many major projects also enforce.  Mybatis is a good example as the entire code base uses the same setup as done here and there is a huge China user base effectively working daily with PRs constantly without issue.

**Comment by velo** [comment] 2016-05-29 09:02
That is the think, all machines I have access to and that already have git install fail to build.  Even appveyor w/o the settings I pointed out don't work.

I don't know how this settings affect or not other code bases, I just know the plugin do not build if you take this out https://github.com/revelc/formatter-maven-plugin/blob/master/appveyor.yml#L16

That is why I released 1.6.0 of my fork, I don't wanna risk my projects being affected by this.

**Comment by hazendaz** [comment] 2016-12-26 18:21
I pushed a release of this as 2.0.0.  It should be in central in next couple of hours.

**Comment by hazendaz** [comment] 2016-12-27 21:51
There are some central sync issues due to maintenance that I've confirmed.  The release is entirely in sonatype releases so good to use but won't show in central for a few days.  Since this has been confirmed via sonatype team, I'm closing this as completed.

**Closed by hazendaz** 2016-12-27 21:51 UTC
Labels: help wanted
