### ISSUE TITLE
Handle join_wrapped_lines option

### ISSUE THREAD

**Issue by maxwo** [revelc/formatter-maven-plugin#289] opened 2018-10-25 06:16 UTC
Hey,

When configuring `join_wrapped_lines` to `false`, the formatter still joins wrapped lines, making it more difficult to read Java builder, stream and reactive structures.
When running the built-in Eclipse formatter, everything goes fine: each new line is kept as expected, but once in our CI, using your maven plugin, we are facing some formatting check issues because of this.

The following code get reduced to a "one-liner", while, for readability, it would make it much easier to keep inserted new lines:

```java
    return stocks
        .values()
        .stream()
        .flatMap(Collection::stream)
        .filter(StatisticsService::isTracked)
        .collect(Collectors.groupingBy(Enum::name, Collectors.counting()));
```

Plugin version: 2.8.0.

Thank you.

**Comment by ctubbsii** [comment] 2018-10-25 07:08
Interesting. The formatter-maven-plugin is a thin wrapper around the same formatting code that formats code in Eclipse, so it's unusual to have formatting differences between the two that don't involve user configuration error, but it can happen.

To assist in debugging, can you provide a minimal maven project which includes the code that should not be joined, along with the pom with the plugin configured and the formatter configuration file, that reproduces this issue?

**Comment by vbence** [comment] 2019-02-12 14:52
Searching for `join_wrapped_lines`  in this repo, only test files and a sample config is found - no code references it.
https://github.com/revelc/formatter-maven-plugin/search?q=join_wrapped_lines&unscoped_q=join_wrapped_lines

My guess, it was removed somewhere along the line.

**Comment by yukihane** [comment] 2019-03-20 01:50
https://github.com/yukihane/sample-formatting

configFile: https://github.com/yukihane/sample-formatting/blob/master/java-code-format.xml
joined Java source: https://github.com/yukihane/sample-formatting/blob/master/src/main/java/com/github/yukihane/Number.java

**Comment by ctubbsii** [comment] 2019-03-20 20:52
Thanks for the sample project! It was very helpful in finding the problem. I filed an upstream bug at https://bugs.eclipse.org/bugs/show_bug.cgi?id=545603

It appears that `org.eclipse.jdt.core.formatter.join_wrapped_lines` being set to `false` is ignored when `org.eclipse.jdt.core.formatter.alignment_for_enum_constants` is set to `0` (and several other values tested). When you import the sample configuration file into Eclipse, it auto-populates the missing `org.eclipse.jdt.core.formatter.alignment_for_enum_constants` entry with a value of `16`. I don't know the significance of `16`, but it causes things to work correctly.

The workaround is to add an entry for `org.eclipse.jdt.core.formatter.alignment_for_enum_constants` with a value of `16`:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<profiles version="15">
<profile kind="CodeFormatterProfile" name="unexpected_joining" version="15">
<setting id="org.eclipse.jdt.core.formatter.alignment_for_enum_constants" value="16"/>
<setting id="org.eclipse.jdt.core.formatter.join_wrapped_lines" value="false"/>
</profile>
</profiles>
```

**Comment by ctubbsii** [comment] 2019-03-20 20:55
It may be possible for the formatter-maven-plugin to work around this bug by auto-merging a partial config with the default settings applied when you manually import a configuration into the Eclipse platform GUI... but I don't know if that's possible, because I'm not sure where those default settings are saved.

**Comment by ctubbsii** [comment] 2019-11-07 06:23
The upstream bug comments indicate this is expected behavior from the Eclipse formatter code, when faced with incomplete configuration. The workaround is to provide a complete export of the current configuration (or at least enough to get the desired behavior, as suggested in my earlier comment in this thread). I recommend following the upstream bug, if this is still an interest to you, but I'm closing this now.

**Closed by ctubbsii** 2019-11-07 06:23 UTC
