### ISSUE TITLE
style checking?   

### ISSUE THREAD

**Issue by danyaljj** [revelc/formatter-maven-plugin#79] opened 2015-10-28 03:57 UTC
I am in need of this behavior: 
1.  format checking done the compile time 
2.  code formatting upon `formatter:format`

No 2 is done by this plugin. 
How about No 1?  Is it possible to do format-checking with this plugin? 

If not, is it possible to use https://maven.apache.org/plugins/maven-checkstyle-plugin/ to do it? 
The important issue is that the styles for the format-checker and code-formatter need to be compatible.

**Comment by velo** [comment] 2015-10-28 06:33
howdy @danyaljj we do have a goal to do so, but it is not released yet.

We do that on this project build using the old release candidate
https://github.com/revelc/formatter-maven-plugin/blob/master/pom.xml#L391


@ctubbsii @mblanchette  @hazendaz ain't time for a release?

**Comment by hazendaz** [comment] 2015-10-28 10:41
I feel there are still issues to be addressed before a release.  For one code won't build for windows user....ie myself and old functionality is missing to use jar with rules.  If both those are restored to working then yes it would be ready.  I've been too busy to get a deeper look as 0.5.2 release suits my needs currently.


Sent by Outlook for Android





On Tue, Oct 27, 2015 at 11:33 PM -0700, "Marvin Froeder" <notifications@github.com> wrote:
howdy @danyaljj we do have a goal to do so, but it is not released yet.

We do that on this project build using the old release candidate
https://github.com/revelc/formatter-maven-plugin/blob/master/pom.xml#L391


@ctubbsii @mblanchette  @hazendaz ain't time for a release?

---

**Comment by hazendaz** [comment] 2015-10-28 11:05
Another thing while thinking about it.  The new version no longer formats during development.  Last we talked you said do it in eclipse first.  That isn't how this plugin is used.  Its ide independent.  We use it in stand alone coding, netbeans, and intellij.  Line endings which I saw someone else trying to also fixed needs resolved.  Most people check out auto which means windows line endings in windows not as is using Unix endings.  I will come back over here this coming weekend to start addressing these concerns.  My biggest concern is breaking all current uses.  I've got this in a major firm so breaking existing will turn off a large user base.  Plus since moving group our usage statistics are growing really fast.  The last thing I want to happen is a breakup on this before it gets going.  Bottom line old one with 0.5.2 works perfectly fine in all use cases.


Sent by Outlook for Android





On Wed, Oct 28, 2015 at 3:41 AM -0700, <jeremylandis@hotmail.com> wrote:
I feel there are still issues to be addressed before a release.  For one code won't build for windows user....ie myself and old functionality is missing to use jar with rules.  If both those are restored to working then yes it would be ready.  I've been too busy to get a deeper look as 0.5.2 release suits my needs currently.


Sent by Outlook for Android





On Tue, Oct 27, 2015 at 11:33 PM -0700, "Marvin Froeder" <notifications@github.com> wrote:
howdy @danyaljj we do have a goal to do so, but it is not released yet.

We do that on this project build using the old release candidate
https://github.com/revelc/formatter-maven-plugin/blob/master/pom.xml#L391


@ctubbsii @mblanchette  @hazendaz ain't time for a release?

---

**Comment by hazendaz** [comment] 2015-10-29 04:59
My concerns at this point are addressed from build perspective.

During normal build I would suggest you have formatter:format configured.  Then when running on CI change that to formatter:validate.  That option will preven it from getting into a master unformatted while allowing developers quick development time to not worry about the plugin.  Basically that means developers need to build first.  I can attest that is skipped often and it hits CI, gets past that point and is discovered on the next checkout by another developer.  So having that set on a CI box to run specifically in automated fashion will ensure those things don't occur.  It will force developers to make sure they built their product first.

**Comment by danyaljj** [comment] 2015-10-29 06:18
Awesome. Thanks for the follow ups. So as I understood you guys going to publish a new version which has `formatter:validate` goal?

**Comment by hazendaz** [comment] 2015-10-29 10:33
Yes that is coming.  We have a number of things to still work out.  We are going through some growing pains.  The original library became two over the years on different paths.  We are attempting to bring them together which has a number of challanges.  We are fairly close but have to address regressions on both ends.  Once we get everything addressed we will push out the first combined effort.  Hopefully soon.  Then I'd expect we will start working on pulling in another library for xml formatting which essentially would make this full featured.  So definitely bare with us and if you see areas to contribute certainly do so.  Thanks


Sent by Outlook for Android





On Wed, Oct 28, 2015 at 11:18 PM -0700, "Daniel Khashabi" <notifications@github.com> wrote:
Awesome. Thanks for the follow ups. So as I understood you guys going to publish a new version which has `formatter:validate` goal?

---

**Comment by danyaljj** [comment] 2015-11-07 02:04
Do you guys have any expected release date?

**Comment by hazendaz** [comment] 2015-11-07 18:55
There are some regressions to deal with still after merging of two projects that was done.  Probably won't be for a few weeks before I can address all issues from the original project head.  I know @velo noted some issues from his end as well that haven't been addressed.  As soon as we can address those, we should be able to move fowards.  I don't want to through a date out yet but I would expect it will be prior to end of the year.  I expect I will be able to resolve regressions on my end in next couple of weeks.

**Comment by danyaljj** [comment] 2015-12-11 17:50
Just checking on you guys if there is any update on this.

**Comment by ctubbsii** [comment] 2015-12-11 18:49
I usually use the checkstyle plugin for verification. I think it works well in conjunction with a good formatter rule. I realize there's discrepancies in syntax and behavior between the configs for both plugins, but I think it's a good combo, and it might be safer to avoid bloating the formatter plugin too much with this extra functionality... at least for now... though I can see merits for it being added at some point.

**Comment by hazendaz** [comment] 2015-12-12 00:56
I think the ask was on the release.  I believe the new code has this functionality.  I'll try to look at this again shortly.  I believe there are trivial bugs to get the old state and new state working.  I'm in a much better position now to do live tests to flush out issues.  I'll see if I can look at this over the weekend.  Honestly though outside of this change and javascript formatting I don't see mars cut really changing anything over version 0.5.2.


Sent from Outlook Mobile






On Fri, Dec 11, 2015 at 10:49 AM -0800, "Christopher Tubbs" <notifications@github.com> wrote:





I usually use the checkstyle plugin for verification. I think it works well in conjunction with a good formatter rule. I realize there's discrepancies in syntax and behavior between the configs for both plugins, but I think it's a good combo, and it might be safer to avoid bloating the formatter plugin too much with this extra functionality... at least for now... though I can see merits for it being added at some point.

---

**Comment by hazendaz** [comment] 2015-12-14 01:41
While we are still trying to get this released, I would suggest in the meantime to go ahead and use @velo project as it provides that out of the box.

```xml
<dependency>
    <groupId>com.marvinformatics.formatter</groupId>
    <artifactId>formatter-maven-plugin</artifactId>
    <version>1.6.0.RC4</version>
</dependency>
```
https://github.com/velo/maven-formatter-plugin

I'm closing this issue since it is present in this code base currently so nothing for us to add other than other word to get released.

**Closed by hazendaz** 2015-12-14 01:41 UTC
Labels: enhancement, question
