### ISSUE TITLE
Formatter cache is not updated for files that were already formatted

### ISSUE THREAD

**Issue by fralalonde** [revelc/formatter-maven-plugin#312] opened 2019-12-05 20:59 UTC
Hash of formatted files is not saved when files were already formatted, which results in the files being  unnecessarily re-formatted on every subsequent pass. For modules with many files, this can become a major performance impediment. 

For example, one of the modules of our legacy project holds nearly 3000 files:
```
[INFO] Number of files to be formatted: 2918
[INFO] Successfully formatted:          2917 file(s)
[INFO] Fail to format:                  0 file(s)
[INFO] Skipped:                         2847 file(s)
[INFO] Read only skipped:               0 file(s)
[INFO] Approximate time taken:          85s
```

**Comment by ctubbsii** [comment] 2019-12-06 00:13
You get this same output every time it runs? That seems strange. I don't see that. For already-formatted files, I see something like:

```
[INFO] Using 'UTF-8' encoding to format source files.
[INFO] Number of files to be formatted: 781
[INFO] Html formatting is skipped
[INFO] Successfully formatted:          0 file(s)
[INFO] Fail to format:                  0 file(s)
[INFO] Skipped:                         781 file(s)
[INFO] Read only skipped:               0 file(s)
[INFO] Approximate time taken:          5s
```

Can you provide an example project to reproduce the problem, so I can verify that the formatting re-occurs on every run, to test your PR in #313? Thanks.

**Comment by fralalonde** [comment] 2019-12-14 04:10
My description of the issue using a large number of files is probably not the best. The problem occurs no matter how many files are formatted but generally goes unnoticed since a few files will be formatted quickly. The cache, when effective, only makes a difference when a large number of source files need to be processed.

I've created new unit tests in #314 to demonstrate the situation: A a cache entry is _not_ added when a new, uncached file is processed by the formatter but remains unchanged because it was already formatted (possilbly by the IDE, or by previous application of the plugin, followed by a `mvn clean`). No matter how many times the plugin executes, such files will stay in "cache limbo", forever reformatted and never skipped which can lead to serious performance issues in larger projects, as decribed above.

**Comment by ctubbsii** [comment] 2019-12-18 05:49
@fralalonde  Internal details about caching aside, it sounds like you're saying that bug causes the user to observe already-formatted files to be "Successfully formatted" on subsequent runs. However, I observe my already-formatted files to be counted as "Skipped", instead, as they should be.

Please help me understand what I'm missing. (I'll try to take a look at your PR #314 soon, but I don't have time today.)

**Comment by fralalonde** [comment] 2020-01-06 19:33
Plainly put: When formatting or validating a clean project, source files that were already formatted are not added to the `formatter-maven-cache.properties` file. Which results in those files being needlessly evaluated again in all further formatting passes even if they did not actually change. 

The problem will manifest on any project with formatted source after a `mvn clean`.

For example, starting with the happy path:
```
git clone git@github.com:fralalonde/fmt-cache-demo.git
cd fmt-cache-demo
mvn formatter:format

[INFO] Number of files to be formatted: 64
[INFO] Successfully formatted:          64 file(s)
[INFO] Fail to format:                  0 file(s)
[INFO] Skipped:                         0 file(s)
[INFO] Read only skipped:               0 file(s)
[INFO] Approximate time taken:          5s

mvn formatter:format

[INFO] Number of files to be formatted: 64
[INFO] Successfully formatted:          0 file(s)
[INFO] Fail to format:                  0 file(s)
[INFO] Skipped:                         64 file(s)
[INFO] Read only skipped:               0 file(s)
[INFO] Approximate time taken:          0s
```
Second pass is much faster than first pass because of the cache skipping files that did not change. Looking at `formatter-maven-cache.properties` one can see entries for every source file:
```
#Mon Jan 06 14:29:18 EST 2020
/src/main/java/MyClass9.java=82c81485dcbb0948a477d837088a87d117118edaf45c823a40f20294a01ce4879d64886c68af341277b92c51ada1c5a28ad56194d18bd818bfdb9396494f529d
/src/main/java/MyClass57.java=ff2e46a726bdbe11c398ed469b32aeda5dd9982f3dc55129333a238a45f196fe48769a088a2ba3716274e2e32d7379d76c4ee7b6583a9fb4d1de8765f8939b8a
/src/main
...
```

Continuing to the pathological path, in the same repo with nothing changed since previous commands ran:
```
mvn clean
mvn formatter:format

[INFO] Number of files to be formatted: 64
[INFO] Successfully formatted:          0 file(s)
[INFO] Fail to format:                  0 file(s)
[INFO] Skipped:                         64 file(s)
[INFO] Read only skipped:               0 file(s)
[INFO] Approximate time taken:          3s

mvn formatter:format

[INFO] Number of files to be formatted: 64
[INFO] Successfully formatted:          0 file(s)
[INFO] Fail to format:                  0 file(s)
[INFO] Skipped:                         64 file(s)
[INFO] Read only skipped:               0 file(s)
[INFO] Approximate time taken:          4s
```

`mvn clean` flushes the cache by deleting `formatter-maven-cache.properties`.
Although the files appear as "skipped" the formatter still get applied on the second pass, resulting in no performance gain from the cache on the second formatter execution.

Looking at the `formatter-maven-cache.properties` reveals that none of the files that were evaluated were cached:
```
#Mon Jan 06 14:33:01 EST 2020
[no entries]
```

**Comment by hazendaz** [comment] 2020-01-07 00:12
Interesting.  I ran into some notes I had upon testing more recently added file types today  and noted there it seemed to keep reformatting files under some conditions.  I had not investigated further.

I think for clarity we should note what is skipped via cache as well.  That would make it more obvious and easier to detect if something goes wrong in the future.  WDYT

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by fralalonde** [comment] 2020-01-07 00:34
Yes, having separate statistics for cache hits could be interesting, although I would not expose it as being a "cache" as this is more akin to "incremental formatting" like a compiler would do. Actually statistics is something else I had ideas for but I'll keep this for a separate issue / PR.

**Comment by ctubbsii** [comment] 2020-01-09 22:11
I can't see this in the output at all. I wonder if this only affects projects that are running `formatter:format` outside of a maven lifecycle on a multi-module project (perhaps because files are found in child directories multiple times in the same execution, once at the parent, and once again when the plugin runs in the child module)? I don't see this at all when the plugin is run on a large multi-module project as part of the default maven lifecycle.

I still think it would help significantly to have an example project on which this can be reproduced easily, with step-by-step instructions to reproduce and verify the problem.

I agree that a new "skipped because no changes detected" output might be useful, either in the default output as a count, or as individual messages for each unchanged file detected (possibly with a debugging flag set). Either way, an example project would still be useful to verify the difference in the output.

**Comment by hazendaz** [comment] 2020-01-14 03:58
When I get some time I plan to look at this more myself.  Right now for me it's not a huge priority only in so much that I'm in-between a lot of other year end stuff still and won't have much time to look at this seriously probably until February.  I do think @ctubbsii you might be onto something.  I suspect I was running that way when I was initially testing feasibility of the xml formatting being turned on which ultimately I did for some pieces in rather large number of projects.  So now I have java, javascript and xml all being formatted but there were some inconsistences I had noted depending how things were ran and for obvious reasons not everything is then formatted.  

Duplicate formatting and even some cases it totally corrupted the formatting depending on how it was approached.  For example, if I'm formatting xml, I want the poms too but opening up that far caused some serious trouble for me throughout.  Anyway, as soon as I clear some other things I want to look more at this timing as roughly March timeframe I should be applying this onto some 200k project where timing is going to considerably matter and the project is already significantly slow kitchen sink.  I think as @fralalonde noted at some point, this is best seen on large scale as the numbers are rather insignificant on small projects but every little bit helps especially for powers that be think we need to no longer have real machines, just vm(s) of vm(s) in some cases that just add to slow...

If the cache were truly working, I suspect the path contained within it would have been different when I more broadly told it to format.  It's also possible formatting could be switched on this plugin to format just the one time, not the maven multi module way.  Regardless, once the normal src/ area is changed its going to pick up too much and if it's not tracking entirely the full build path as it moves through it would fail the cache for those reasons as well.  I haven't looked but it would at a minimum need the module it's in (parent or child) along with the file so it skips those as well.

**Comment by ctubbsii** [comment] 2020-01-17 04:06
I think I misunderstood the key point that the cache was intended to be reused across multiple executions of the plugin. That's not how I use Maven (I always do clean builds), but I still should have understood that earlier. I was too focused on the idea that the cache (which I think isn't well documented) was intended to be used within a single execution... perhaps to avoid reformatting duplicate files in the repo or something similar, and clobbered on each new execution of the plugin. That's obviously not the case, as I now understand it.

So, yeah, a good test case for this would be nice to avoid the regression... but the test should pass on a clean checkout of this project, and also subsequent builds of this plugin without cleaning. Writing such a test might be easier if the location or name of the cache file were configurable.

In any case, I think the first step is one that adds output information about the cache utilization, so we can actually see from the output when it's working and when it isn't.

**Comment by fralalonde** [comment] 2020-01-21 19:46
Would you like me to submit a PR for that?

**Comment by fralalonde** [comment] 2020-01-21 20:52
> I still think it would help significantly to have an example project on which this can be reproduced easily, with step-by-step instructions to reproduce and verify the problem.

BTW this is what I did for my example above, I created a Maven project just for this. You should be able to follow the instructions and reproduce the issue by entering the same commands. 

1. clone sample project
```
git clone git@github.com:fralalonde/fmt-cache-demo.git
cd fmt-cache-demo
```

2. format dirty files from project, slow because project is large and cache is empty

> mvn formatter:format

3. format _again_ dirty files from project, fast because last results were cached

> mvn formatter:format

4. Look at cache file in target, see entries
5. Delete formatting cache file, but keep formatted files

> mvn clean

6. format _clean_ files from project, slow because project is large and cache is empty

> mvn formatter:format

7. **bug is here** format _clean_ files from project, slow because project is large and cache is **still** empty

> mvn formatter:format

8. Look at cache file in target, see **no** entries

**Comment by hazendaz** [comment] 2020-06-27 16:00
@ctubbsii @fralalonde Looking at this again for fix with our next release.  I'm going to submit a pull request of my own that I believe addresses this issue as expected.

The PR #313 will not fix this issue properly.  All that PR will do is indicate formatting occurred and load the cache.  The second item of loading the cache is what the issue you are trying to solve is intended to do.  It however did not format the file and would therefore cause other side effects such as writing the file anyways which won't improve things at all on the first run.  An empty cache itself should not result in it writing files at all if there is nothing to actually format.  The PR would actually ensure it always wrote at least once which isn't what any of us ultimately want.

The real issue is addressing the cache getting loaded.  Currently what is correct is that if the file is found in the cache and it's hash matches, it will skip even trying to format.  That part we can agree is solid.  When it goes into formatting, it needs to still ensure it either did or did not format.  The real problem is the cache write being skipped because we get out of the mojo when we flagged the file as skipped.  We however simply failed to add that skipped frile to the cache.  That is the key problem.

So how to really fix this, I think its actually easy.  We need to simply stop getting out before writing the cache.  If file was flagged as skipped, we need to 'break' instead of 'return'.  That will allow it to run through the logic to populate the cache.  In fact, the logic really looks like this was even expected but we break out too soon for that to work.  Finally, we just need exit out on skipped items before we check originalHash being equal to formatted hash.  I sort of think that check current is just an additional safety hook.  We already indicated it was skipped so I'm not quite sure how it would have actually matched but none the less it's probably for other formatters and not a specifically bad check just to be sure.

There are still other issues with this.  The READ happens numerous times on the file.  When checking the cache, inside the formatter itself, then again to write teh case.  I think we eventually should address that too in order to speed this up more as that is a bit unnecessary to do numerous times. It also ends up writing it multiple times too.  In case of java for sure, it uses the formatter to write the file then comes back to the mojo and does it again.  I think that might be why the safety check was in place but obviously a bit off.

Another problem which I have a fix for now is where we place this cache to start with.  I think generally a developer is going to run clean fairly often.  I know personally I run mvn clean install most of the time.  That will just zap the cache and I don't see any valid reason for doing so.  That said, I'll have another PR that will move the cache to .cache folder in project so it's not cleaned by maven.  While that could always be changed, I'm leaning towards our default simply changing so it improves processing.

While I think there is a need for a lot of work in this area, I'm not sure how much will get done before the next release.  I think at very minimum this specific issue is addressed, the default cache is changed, and other issues are further documented as outstanding.

**Comment by hazendaz** [comment] 2020-06-27 16:52
I've actually rewritten most of the logic now so I think the next release will see a complete fix of this so it no longer is reading and writing multiple times in addition to the caching fixes.  I'm testing it all now but effetively instead of passing the File location around, I'm passing the originalCode it already read and using the formattedCode it returned.  The check on original hash to formatted hash now makes some sense as it was IMO a bad call to fix original issues many years ago.

**Comment by hazendaz** [comment] 2020-06-27 19:37
fixed in master.

**Closed by hazendaz** 2020-06-27 19:37 UTC
