### ISSUE TITLE
Java files have status changed on every execution

### ISSUE THREAD

**Issue by GoogleCodeExporter** [revelc/formatter-maven-plugin#19] opened 2015-03-14 02:49 UTC
```
What steps will reproduce the problem?
1. Inspect a java file, note the time of the last filesystem stat change.
2. Run java-formatter-plugin
3. Note even if no changes were required to the java file the last status 
change has been changed.

When no formatting changes are required, it would be preferable if the java 
file was unmodified.  

I'm using version 0.3 on MacOSX, as part of the OpenMRS project.

For code editors that use the last stat change date (such as emacs) to detect 
file changes, this prompts the developer every time the java-formatter-plugin 
runs, even when it made no changes.

```

Original issue reported on code.google.com by `greghear...@gmail.com` on 7 Jun 2012 at 12:56

**Comment by hazendaz** [comment] 2015-05-10 13:51
Is this something only seen on non windows systems?  I always run clean install and I've never seen this occur in windows.

**Comment by ctubbsii** [comment] 2015-05-13 18:11
This is so old. Let's close it for now. If it re-occurs, we can address it later.

**Closed by ctubbsii** 2015-05-13 18:11 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect

**Comment by Shredder121** [comment] 2016-09-11 09:22
Just a small heads up:
The issue is present when you use `core.autocrlf input` I believe.
At least, I'm on Windows, and rather work with what's in the repository than with CRLF, so you can see earlier when people haven't set up their git correctly.

But if git has checked out one line ending style and watches that format, and the plugin then writes out CRLF, git sees that the file has changed.

It's not that big of a deal, since you can solve it by using `core.autocrlf true`.

**Comment by hazendaz** [comment] 2016-09-11 16:24
We do expect auto true.  And eventually will turn on a ci hook that will prevent code making it in with improper line endings.  At least on the travis / appvoyer builds by making them fail.

Get Outlook for Android<https://aka.ms/ghei36>



On Sun, Sep 11, 2016 at 5:22 AM -0400, "Ruben Dijkstra" <notifications@github.com<mailto:notifications@github.com>> wrote:


Just a small heads up:
The issue is present when you use core.autocrlf input I believe.
At least, I'm on Windows, and rather work with what's in the repository than with CRLF, so you can see earlier when people haven't set up their git correctly.

But if git has checked out one line ending style and watches that format, and the plugin then writes out CRLF, git sees that the file has changed.

It's not that big of a deal, since you can solve it by using core.autocrlf true.

-

**Comment by hazendaz** [comment] 2016-09-11 16:40
Let me clarify a bit in case the question was about usage not working in our code base.

1) Working in our codebase.

      * We use git attributes to control line endings.
      * Eclipse egit doesn't support git attributes.
      * The settings used are highly typical of git projects on github.
      * Users can locally use whatever they want to build but if they commit with egit, it will cause problems if they did not setup their git properly with core.autocrlf true.
      * We can control / prevent introduction of wrong line endings on entirely new files by using our ci prevention.  For existing files it's pretty easy to see on the diff that someone didn't have git setup correctly.

2) If working on your own code base using this plugin.

      * If you do not use 'auto' due to egit usage, then modify the parameters to run the plugin.

```java
    /**
     * Sets the line-ending of files after formatting. Valid values are:
     * <ul>
     * <li><b>"AUTO"</b> - Use line endings of current system</li>
     * <li><b>"KEEP"</b> - Preserve line endings of files, default to AUTO if
     * ambiguous</li>
     * <li><b>"LF"</b> - Use Unix and Mac style line endings</li>
     * <li><b>"CRLF"</b> - Use DOS and Windows style line endings</li>
     * <li><b>"CR"</b> - Use early Mac style line endings</li>
     * </ul>
     * 
     * @since 0.2.0
     */
    @Parameter(defaultValue = "AUTO", property = "lineending", required = true)
    private LineEnding lineEnding;
```
