### ISSUE TITLE
Failure using Oxygen.1a version (2.7.1): "Workspace is closed." error

### ISSUE THREAD

**Issue by ctubbsii** [revelc/formatter-maven-plugin#260] opened 2017-11-17 01:37 UTC
I tried to run the 2.7.1 version with the patch from #259 on Apache Fluo, but there is a problem. It results in the following error about "Workspace is closed." Googling for this error results in a hint that there may be some problem with the MANIFEST.MF in the JDT dependency. Version 2.7.0 works fine, which uses the org.eclipse.jdt version of jdt-core 3.13.0, instead of the version from org.eclipse.tycho.

The 2.7.1 version works fine on some other projects, such as Apache Accumulo, so I'm not sure what the problem could be. It could be that there's something else on the class path while building the larger Apache Accumulo project, which satisfies whatever requirement is causing the IllegalStateException with the "Workspace is closed." message, but I don't know what that could be.

```
[ERROR] Failed to execute goal net.revelc.code.formatter:formatter-maven-plugin:2.7.1:format (format-source) on project fluo-api: Execution format-source of goal net.revelc.code.formatter:formatter-maven-plugin:2.7.1:format failed: Workspace is closed. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal net.revelc.code.formatter:formatter-maven-plugin:2.7.1:format (format-source) on project fluo-api: Execution format-source of goal net.revelc.code.formatter:formatter-maven-plugin:2.7.1:format failed: Workspace is closed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution format-source of goal net.revelc.code.formatter:formatter-maven-plugin:2.7.1:format failed: Workspace is closed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: java.lang.IllegalStateException: Workspace is closed.
	at org.eclipse.core.resources.ResourcesPlugin.getWorkspace(ResourcesPlugin.java:412)
	at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.createParser(DefaultCodeFormatter.java:332)
	at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.parseSourceCode(DefaultCodeFormatter.java:317)
	at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.prepareFormattedCode(DefaultCodeFormatter.java:213)
	at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.prepareFormattedCode(DefaultCodeFormatter.java:206)
	at org.eclipse.jdt.internal.formatter.CommentsPreparator.formatCode(CommentsPreparator.java:1063)
	at org.eclipse.jdt.internal.formatter.CommentsPreparator.handleFormatCodeTag(CommentsPreparator.java:801)
	at org.eclipse.jdt.internal.formatter.CommentsPreparator.handleHtml(CommentsPreparator.java:665)
	at org.eclipse.jdt.internal.formatter.CommentsPreparator.endVisit(CommentsPreparator.java:621)
	at org.eclipse.jdt.core.dom.TagElement.accept0(TagElement.java:282)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2796)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2867)
	at org.eclipse.jdt.core.dom.Javadoc.accept0(Javadoc.java:205)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2796)
	at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.prepareComments(DefaultCodeFormatter.java:399)
	at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.prepareFormattedCode(DefaultCodeFormatter.java:222)
	at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.format(DefaultCodeFormatter.java:177)
	at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.format(DefaultCodeFormatter.java:160)
	at net.revelc.code.formatter.java.JavaFormatter.doFormat(JavaFormatter.java:46)
	at net.revelc.code.formatter.AbstractCacheableFormatter.formatFile(AbstractCacheableFormatter.java:47)
	at net.revelc.code.formatter.FormatterMojo.doFormatFile(FormatterMojo.java:511)
	at net.revelc.code.formatter.FormatterMojo.formatFile(FormatterMojo.java:466)
	at net.revelc.code.formatter.FormatterMojo.execute(FormatterMojo.java:344)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :fluo-api
```

**Comment by hazendaz** [comment] 2017-11-17 01:58
Interesting.  I was trying to create a plugin last year to auto add javadocs using jautodoc.  I gave up with teh same error you see here.  Now that makes me want to go back and review all the dependencies I was using to see if I can actually make that work.

On a side note, running into some other issues.  I configured the plugin to work with m2e and it causes lots of issues right now with what I think is class loading problems in eclipse.  I'll get some more details and open a ticket as soon as I have more time to look into the issue.

**Comment by wborn** [comment] 2017-12-01 16:54
For me the issue only occurs when formatting Java code with comments that contain HTML. It occurs for instance when formatting the following file:

```
package com.hello.world;

/**
 * <pre>
 * Hello World
 * </pre>
 */
public class HelloWorld
{
}
```

An easy way to reproduce it is by adding a test to `JavaFormatterTest.java` that tries to format a file with this content.

The issue seems to be introduced by the changes for:

>  Issue: [Bug 506430 - [1.9] Formatter support for module-info.java](https://bugs.eclipse.org/bugs/show_bug.cgi?id=506430)
> Commit: https://github.com/eclipse/eclipse.jdt.core/commit/49e9d0cec84062b8f937bcce9ab15ec576e3a013

In this commit `DefaultCodeFormatter.java` also tries to `parseSourceCode(..)` using a `K_MODULE_INFO` type (Java 9). As a result there is now a also a call to `ResourcesPlugin.getWorkspace()` while this bundle is not started. Resulting in the `Workspace is closed` exception.

What could solve the issue is:
* somehow getting it to skip trying the `K_MODULE_INFO` type although there is no hook for this in the DefaultCodeFormatter
* proper exception handling in DefaultCodeFormatter when there is no workspace
* getting a non-null workspace in the ResourcesPlugin

Some other workarounds instead of reverting to formatter-maven-plugin 2.7.0 are:
* removing HTML from comments
* adding `@formatter:off` and  `@formatter:on` to these comments

**Comment by ctubbsii** [comment] 2017-12-01 22:48
@wborn Thanks for investigating this. Do you know if there's an upstream bug already open regarding this? It seems like there's going to need to be if we want to avoid requiring the use of one of these workarounds long-term.

**Comment by wborn** [comment] 2017-12-02 09:30
@ctubbsii There is no known upstream issue that I am aware of.

But I have found a better workaround for this issue by disabling HTML formatting from within the configuration by updating the following two parameters to false:

```
<setting id="org.eclipse.jdt.core.formatter.comment.format_html" value="false"/>
<setting id="org.eclipse.jdt.core.formatter.comment.format_source_code" value="false"/>
```

This way you don't have to touch any code and can simply change the parameters to true when the issue us fixed. :slightly_smiling_face:

**Comment by ctubbsii** [comment] 2017-12-04 02:09
It's good to have a lot of workarounds, so thanks for the ideas. However, if upstream doesn't know about the issue, then it's not ever going to be fixed.

@wborn , you seemed to have the most complete understanding of why it's happening. If you wouldn't mind creating an upstream issue at the Eclipse bugtracker at https://bugs.eclipse.org/bugs, I would very much appreciate it. If you don't have an account and don't want to make one, I can do it in a few days, but since I don't have a very good understanding of the problem, I won't be able to help the Eclipse developers troubleshoot it. I'll probably just be able to point them back to your comments on this thread. :smile:

**Comment by wborn** [comment] 2017-12-04 10:38
@ctubbsii I've submitted the following issue: https://bugs.eclipse.org/bugs/show_bug.cgi?id=528085

**Comment by pierrefevrier** [comment] 2017-12-21 16:45
Hi, I have the same problem, when do you plan to release v2.7.2 ?

**Comment by ctubbsii** [comment] 2017-12-21 16:55
As soon as upstream fixes the bug, we can do a release.

**Comment by jmini** [comment] 2017-12-24 09:17
In order to help with the upstream issue in the Eclipse bugzilla, I have added a simple class with a `main` method that reproduces the problem: [MainFormatter.java, see Comment 3](https://bugs.eclipse.org/bugs/show_bug.cgi?id=528085#c3)

For my tests, I have used the latest jdt version available on Maven Central:

    <dependency>
      <groupId>org.eclipse.jdt</groupId>
      <artifactId>org.eclipse.jdt.core</artifactId>
      <version>3.13.100</version>
    </dependency>

Thanks you *wborn* for you detailed analysis.

**Comment by jmini** [comment] 2018-01-10 07:46
This issue was fixed in the upstream project with commit: https://github.com/eclipse/eclipse.jdt.core/commit/41b609123705d8e31de5555a8c4ed6a6ac0229b6

I think that the fix will be published with the [Oxygen.3](https://wiki.eclipse.org/Oxygen/Simultaneous_Release_Plan#Oxygen.3) release in March 2018. Around after this date, a new version should be available on maven central.

**Comment by ctubbsii** [comment] 2018-01-25 22:23
It looks like the version of the JDT core jar will be 3.14.0, so anything newer than that should have the fix.

**Comment by ctubbsii** [comment] 2018-02-02 12:16
Here's a [link][1] to the Maven Central search results to more easily check for when the updated version is published. (Saves me from periodic manual searching.)

[1]: http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.eclipse.jdt%22%20AND%20a%3A%22org.eclipse.jdt.core%22

**Comment by jmini** [comment] 2018-03-27 08:54
Now that Oxygen.3 is out, I have [asked](https://dev.eclipse.org/mhonarc/lists/jdt-dev/msg00992.html) on the JDT Mailing list when the artifact will be published on Maven Central.

**Closed** 2018-03-29 22:20 UTC
Labels: help wanted

**Comment by ctubbsii** [comment] 2018-03-29 23:13
Version 2.7.2 of this plugin is now tagged and also released to Maven Central. Website has also been updated to reflect this.
