### ISSUE TITLE
False configuration used for line Indentation

### ISSUE THREAD

**Issue by oalagtash** [revelc/formatter-maven-plugin#801] opened 2023-11-03 15:36 UTC
I used the google formatter for eclipse as xml configuration. But instead of 2 indents, 4 indents were used.

Formatter.xml I used: https://github.com/google/styleguide/blob/gh-pages/eclipse-java-google-style.xml

Style Guide where it says it should be two indents: https://google.github.io/styleguide/javaguide.html#s4.2-block-indentation 

A solved Issue that might help clarify the confusion here: https://github.com/google/styleguide/issues/98 

I assume this plugin is wrongly using this configuration: https://github.com/google/styleguide/blob/6ebcd8cee24e6eb5e56efaec55d44873eb224f97/eclipse-java-google-style.xml#L99 

The correct one would be: https://github.com/google/styleguide/blob/6ebcd8cee24e6eb5e56efaec55d44873eb224f97/eclipse-java-google-style.xml#L170C1-L170C1

**Comment by ctubbsii** [comment] 2023-11-20 23:13
If you're seeing a discrepancy between what happens when you import your config into Eclipse and what happens when you use your formatter config in this plugin, it's very likely because the Eclipse JDT library inserts different defaults for missing entries when using an older version of an exported configuration file, depending on if you're using the UI or if you're using the API. This plugin uses the JDT API directly. See https://bugs.eclipse.org/bugs/show_bug.cgi?id=545603#c2

As for the Google Style, this plugin isn't using any of that. The built-in default formatting might have originally been based on the Google Style, but it isn't anymore. It has been updated to comply with newer Eclipse features and may or may not match that style. You can do this yourself by importing an older configuration (such as your preferred Google Style config) into a newer version of Eclipse, and then exporting it to a new file, and configuring this plugin to use that newly exported file.

**Comment by ctubbsii** [comment] 2023-11-20 23:14
Closing this as it's not a bug... just a difference in expected behavior due to the plugin defaulting to using a different configuration than one the user prefers.

**Closed by ctubbsii** 2023-11-20 23:14 UTC
Labels: question
