### ISSUE TITLE
Setting column width

### ISSUE THREAD

**Issue by roosemberth** [revelc/formatter-maven-plugin#138] opened 2016-09-23 10:25 UTC
Hello,

I'd like to change the default column width from 80 columns to 120 columns. Can you please tell me how can I do such change?

Bests Regards,
Roos

**Comment by roosemberth** [comment] 2016-09-23 13:39
Dirty hack:
Specify an eclipse config file with the following lines:
```xml
<setting id="org.eclipse.jdt.core.formatter.tabulation.size" value="4"/>
<setting id="org.eclipse.jdt.core.formatter.comment.line_length" value="140"/>
```

I'd still like to know the proper way of doing this

**Comment by hazendaz** [comment] 2016-10-02 00:48
Normally you configure your own eclipse format settings in eclipse, export that, and then use that with your builds.  It's not exactly a hack in doing so.  This project simply uses what you provide it.

**Comment by hazendaz** [comment] 2016-10-02 00:49
Closing as this isn't really an issue and is more of mis-understanding in how eclipse does it's formatting.

**Closed by hazendaz** 2016-10-02 00:48 UTC

**Comment by roosemberth** [comment] 2026-07-16 08:05
I'm surprised to see activity in this issue, almost 10 years later. I no-longer do Java, but I still believe it makes sense for the feature to be part of this project.

The purpose of the project (per its README) is to _ensure consistent formatting for a project, regardless of differences between IDE preferences or IDE versions that developers use_; the “Dirty hack” I commented above is to set the (Eclipse) IDE preferences.

IMHO, this is not a solution for people using other IDEs: Having each developer configure their IDE defeats the purpose of using this project.

**Comment by ctubbsii** [comment] 2026-07-17 03:02
@roosemberth The only activity was updating the closed status to one that indicates the reason ("not planned"), which was not available when this issue was originally closed. I updated many tickets after some triage to make sure the ones that are closed normally (i.e. with a fix that was applied) were properly marked with a milestone.

As for your feature request, the "dirty hack" you mentioned above is the actual mechanism this plugin uses. So, it's not a hack... it's the intended behavior. Essentially, you're asking for the ability to configure a formatter option... and the right way to do that is in the config you already identified. That's precisely how those options are configured. Since the feature is already implemented and available, then there is nothing to do.
