### ISSUE TITLE
Support for Eclipse Save Actions

### ISSUE THREAD

**Issue by maggu2810** [revelc/formatter-maven-plugin#97] opened 2016-03-06 22:44 UTC
The Eclipse IDE support Save Actions for Java files.
There are additional actions that are not covered by the formatter.
For example you can configure that the final keyword should be used where possible (IMHO a good practice).
I think this includes also #51

**Comment by hazendaz** [comment] 2016-03-10 02:27
@maggu2810 is it possible that you could add this logic?  I'm all for it but don't have much time to spend in this area.

**Comment by maggu2810** [comment] 2016-03-10 09:43
Same here... But if I find some time, I will have a look at.

**Comment by bjakke** [comment] 2017-02-16 07:03
I have long searched for a solution to apply save actions automatically. The problem is that those cannot be exported to an .xml file nor be applied to a codebase (at least not to my knowledge, the only option is to save each file manually in the editor). However recently I figured out there is also Clean Up formatter that can be exported to xml and applied via Source->Clean Up to entire source trees. Not sure if they contain 100% same settings but most of it seems to be same. 

Could it be possible to implement this issue just by running the Clean Up .xml as e.g. configFileCleantUp setting? 

Bonus points if it is possible to configure Members Sort Order (Java->Appearance->Members Sort Order), as that setting seems to be global (i.e. non-exportable to .xml) and influences in which order members are sorted for the "Sort members" action.

**Comment by maggu2810** [comment] 2017-03-02 10:09
I really great feature would be if the plugin could handle Oomph setup files.
This files could contain the whole Eclipse IDE setup, so also save actions, clean up rules, formatter, ...

But similar to @hazendaz, I have no time to implement this feature myself.

**Comment by ctubbsii** [comment] 2018-11-01 17:51
I think it might be better to pursue Eclipse upstream adding configuration options to the formatting code which support the missing "save action" features that aren't already in the formatting code. The weirdest part of this for me is that they have two separate, overlapping, formatting features.

**Comment by hazendaz** [comment] 2024-03-17 05:23
Closing issue as out of scope for formatter plugin.  I agree it would be nice to have a save event but as it stands this is not the right plugin for such as it only deals with formatting.  I also think latest Eclipse may have gotten rest of the mixed usage and formatting is an option there now in save to address.  However, if something is still missing, let us know so long it is for formatting only.

**Closed by hazendaz** 2024-03-17 05:23 UTC
